<?php

/**
 * @file
 * Contains media.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_help().
 */
function ts_media_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the media module.
    case 'help.page.media':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Media module for Drupal 8') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_views_pre_render().
 *
 * Adds the media.view library to the media views.
 */
function ts_media_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'media_library' || $view->storage->id() == 'global_media_library')) {
    $view->element['#attached']['library'][] = 'ts_media/view';
  }
}


/**
 * Implements hook_form_alter().
 */
function ts_media_form_alter(&$form, FormStateInterface &$form_state) {
  if ($form['#form_id'] == 'entity_browser_media_library_form') {
    // Style the submit button.
    $form['actions']['submit']['#attributes']['class'][] = 'button--primary';
    $form['actions']['submit']['#attributes']['class'][] = 'entity-browser-modal-target';
  }
}
/**
 * Implements hook_menu_local_actions_alter().
 *
 * Adds the add media button from media_entity on library pages.
 */
function ts_media_menu_local_actions_alter(&$local_actions) {
  $local_actions['media.add']['appears_on'][] = 'view.media_library.user_media_library';
  $local_actions['media.add']['appears_on'][] = 'view.media_library.global_media_library_page';
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function ts_media_menu_links_discovered_alter(&$links) {
  // Media entity module provides a default view which we disable. Since it also
  // provides a link entry for it we need to update the route there to point to
  // the media library we provide.
  $links['entity.media.collection']['route_name'] = 'view.media_library.global_media_library_page';
}
